name: Build FontLens APK

on:
  push:
    branches: [ main, master ]
  # pull_request:
    # branches: [ main, master ]
  workflow_dispatch:

# env:
  # FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle distribution (bin.zip)
        uses: actions/cache@v5
        with:
          path: ~/.gradle/wrapper/dists
          key: gradle-dist-8.7
          restore-keys: gradle-dist-8.7

      - name: Cache Gradle build cache
        uses: actions/cache@v5
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ hashFiles('**/*.gradle*') }}
          restore-keys: gradle-cache-

      - name: Download gradle-wrapper.jar
        run: |
          mkdir -p gradle/wrapper
          curl -Lo gradle/wrapper/gradle-wrapper.jar \
            https://github.com/gradle/gradle/raw/v8.7.0/gradle/wrapper/gradle-wrapper.jar

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false"

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: FontLens
          path: app/build/outputs/apk/debug/app-debug.apk
          archive: false
          retention-days: 30

  # release:
    # name: Build Release APK (unsigned)
    # runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    # steps:
      # - name: Checkout code
        # uses: actions/checkout@v4

      # - name: Set up JDK 17
        # uses: actions/setup-java@v4
        # with:
          # java-version: '17'
          # distribution: 'temurin'

      # - name: Download gradle-wrapper.jar
        # run: |
          # mkdir -p gradle/wrapper
          # curl -Lo gradle/wrapper/gradle-wrapper.jar \
            # https://github.com/gradle/gradle/raw/v8.7.0/gradle/wrapper/gradle-wrapper.jar

      # - name: Grant execute permission to gradlew
        # run: chmod +x gradlew

      # - name: Build release APK
        # run: ./gradlew assembleRelease --stacktrace

      # - name: Upload release APK
        # uses: actions/upload-artifact@v4
        # with:
          # name: FontLens-release-unsigned
          # path: app/build/outputs/apk/release/app-release-unsigned.apk
          # retention-days: 30
